---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Values.DBname}}
  labels:
    app: wordpress
spec:
  accessModes:
    - {{.Values.Modes}}
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-mysql
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: mysql
    spec:
      containers:
      - image: {{.Values.image}}
        name: {{.Values.dbname}}
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: ROOT
        ports:
        - containerPort: {{.Values.dbport}}
          name: {{.Values.dbname}}
        volumeMounts:
        - name: database-persistent-storage
          mountPath: {{.Values.mpoint}}
      volumes:
      - name: database-persistent-storage
        persistentVolumeClaim:
          claimName: {{.Values.DBname}}
 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Values.wname}}
  labels:
    app: wordpress
spec:
  accessModes:
    - {{.Values.Modes}}
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - image: {{.Values.wordpressimage}}
        name: {{.Values.servername}}
        env:
        - name: {{.Values.env.name}}
          value: {{.Values.env.name}}
        - name:  {{.Values.env.namep}}
          value: {{.Values.env.valuep}}
        ports:
        - containerPort: {{.Values.serverport}}
          name: {{.Values.servername}}
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim: 
             claimName: {{.Values.wname}}


