---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.servername}}
  labels:
    app: wordpress
spec:
   type: ClusterIP
   ports: 
      - port: {{.Values.serverport}}
        targetPort: {{.Values.serverport}}
   selector:
    app: wordpress
    tier: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
  labels:
    app: wordpress
spec:
  ports:
    - port: {{.Values.dbport}}
  selector:
    app: wordpress
    tier: mysql
  clusterIP: None
